checkpoint_path: train_root_dir/Transformer_Diffusion/checkpoint/09-12-02PM-37-11/epoch=0725-loss=0.01119.ckpt

eval_output_path: log/TF-Diff/

t5_max_sentence_length: 128

equal_part_threshold: 0.2

gensdf_latentcode_evaluator:
  gensdf_model_path: null
  resolution: 16
  max_batch: 262144         # 2 ^ 18


input_text: ' '