checkpoint_path: train_root_dir/Transformer_Diffusion/checkpoint/09-18-02PM-33-26/epoch=1392-loss=0.14712.ckpt

eval_output_path: log/TF-Diff/

t5_max_sentence_length: 128

equal_part_threshold: 0.2

gensdf_latentcode_evaluator:
  gensdf_model_path: null
  resolution: 16
  max_batch: 262144         # 2 ^ 18


input_text: A USB device with a hinged mechanism where the front part can pivot upwards, revealing or concealing the USB connector.