checkpoint_path: /root/autodl-tmp/TransArticulate/train_root_dir/Transformer_Diffusion/checkpoint/09-04-09PM-28-04/epoch=0393-loss=0.00000.ckpt

eval_output_path: log/TF-Diff/

t5_max_sentence_length: 128

equal_part_threshold: 0.05

gensdf_latentcode_evaluator:
  gensdf_model_path: null
  resolution: 16
  max_batch: 262144 # 2 ^ 18