checkpoint_path: train_root_dir/Transformer_Diffusion/checkpoint/09-24-11PM-46-52/epoch=1401-loss=0.01127.ckpt

eval_output_path: log/TF-Diff/

t5_max_sentence_length: 128

gensdf_latentcode_evaluator:
  gensdf_model_path: null
  resolution: 16
  max_batch: 262144         # 2 ^ 18


input_text: A toilet features a lid on the tank that can be lifted to access the internal mechanisms, and a hinged seat and lid on the bowl that can be lifted upwards for use and cleaning. # features a main vertical cabinet structure with a horizontal shelf that can slide out from the side, allowing access to items stored on the shelf.

# This storage furniture features a main vertical cabinet structure with a horizontal shelf that can slide out from the side, allowing access to items stored on the shelf.
# A toilet features a lid on the tank that can be lifted to access the internal mechanisms, and a hinged seat and lid on the bowl that can be lifted upwards for use and cleaning.