checkpoint_path: train_root_dir/Transformer_Diffusion/checkpoint/09-09-07PM-54-17/epoch=1288-loss=0.00000.ckpt

eval_output_path: log/TF-Diff/

t5_max_sentence_length: 128

equal_part_threshold: 0.2

gensdf_latentcode_evaluator:
  gensdf_model_path: null
  resolution: 16
  max_batch: 262144 # 2 ^ 18